import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext): void {
  const generateWikiCommand = vscode.commands.registerCommand('texWiki.generateWiki', async () => {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];

    if (!workspaceFolder) {
      vscode.window.showWarningMessage('Tex Wiki needs an open folder to generate a wiki.');
      return;
    }

    const wikiFolder = vscode.Uri.joinPath(workspaceFolder.uri, 'tex-wiki');
    const indexFile = vscode.Uri.joinPath(wikiFolder, 'README.md');
    const workspaceName = workspaceFolder.name;

    const content = buildInitialWikiIndex(workspaceName);

    await vscode.workspace.fs.createDirectory(wikiFolder);
    await vscode.workspace.fs.writeFile(indexFile, Buffer.from(content, 'utf8'));

    const document = await vscode.workspace.openTextDocument(indexFile);
    await vscode.window.showTextDocument(document);

    vscode.window.showInformationMessage('Tex Wiki generated the initial wiki structure.');
  });

  context.subscriptions.push(generateWikiCommand);
}

export function deactivate(): void {}

function buildInitialWikiIndex(workspaceName: string): string {
  return `# ${workspaceName} Wiki

Generated by Tex Wiki.

## Overview

This is the first wiki structure generated from the active VS Code workspace.

## Proposed Sections

- Project overview
- Architecture
- Main flows
- Directory map
- Setup and execution
- Deployment
- Operational notes
- Glossary

## Initial Flow

\`\`\`mermaid
flowchart TD
    A[Open workspace in VS Code] --> B[Run Tex Wiki: Generate Wiki]
    B --> C[Scan project directory]
    C --> D[Create wiki structure]
    D --> E[Write Markdown files]
    E --> F[Review and enrich documentation]
\`\`\`

## Next Implementation Steps

- Scan files and folders from the active workspace.
- Ignore directories such as node_modules, dist, build and .git.
- Generate one Markdown page per relevant area.
- Add Mermaid diagrams for architecture and main flows.
- Add configurable output folder and ignore patterns.
`;
}
